info.emp.name=Sachin
info.emp.id=232435454

#Array Properties
info.emp.skills[0]=Java
info.emp.skills[1]=Advanced Java
info.emp.skills[2]=Python
info.emp.skills[3]=Advanced Python

#List Propertis
info.emp.team-members[0]=nitin
info.emp.team-members[1]=rajiv
info.emp.team-members[2]=ravi

#Set Properties
info.emp.phone-numbers[0]=215131313
info.emp.phone-numbers[1]=464646446
info.emp.phone-numbers[2]=899845615

#Map properties
info.emp.id-details.adharCard=56456461
info.emp.id-details.panNo=NMFD5546
info.emp.info.details.votarCard=1553SS

#HAS-A 
info.emp.company.name=Accenture
info.emp.company.size=67
info.emp.company.location=Delhi
