spring.application.name=BootMVCProj-1-DisplayingHomePage
server.port=9091

#information for view-resolver
spring.mvc.view.prefix=/WEB-INF/pages/
spring.mvc.view.suffix=.jsp

#context-path
server.servlet.context-path=/firstApp
