spring.application.name=BootMVCProj-8-SpringMVC_CRMProjectJSP
server.port=9091
spring.mvc.view.prefix=/WEB-INF/pages/
spring.mvc.view.suffix=.jsp

server.servlet.context-path=/CRM


#mysql

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql:///enterprisebatch
spring.datasource.username=root
spring.datasource.password=root

#hibernate setup

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect