spring.application.name=SpringCloud-Reslilience4j
management.health.circuitbreakers.enabled=true
management.health.ratelimiters.enabled=true
management.endpoints.web.exposure.include=*
server.port=9999
resilience4j.circuitbreaker.instances.orderdetails.register-health-indicator=true
resilience4j.circuitbreaker.instances.orderdetails.sliding-window-size=5
resilience4j.circuitbreaker.instances.orderdetails.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.orderdetails.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.orderdetails.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.orderdetails.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.orderdetails.automatic-transition-from-open-to-half-open-enabled=true